spring.application.name=SD_12_PoloHaven
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=datn_sd14;sendStringParametersAsUnicode=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.generate-ddl=true
logging.level.net.ttddyy.dsproxy.listener=debug
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type=trace
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.format_sql=true
jwt.signerKey=dPwfR7cghCw7V6xFm47kJcbftwri5sX2qjpnfHOTC3lyp7D5TsEhRNs40RWXbgiZ

# ??m b?o to�n b? request/response, websocket ??u UTF-8
#spring.web.encoding.charset=UTF-8
#spring.web.encoding.force=true
#spring.web.encoding.enabled=true

# Jackson serialize UTF-8
#spring.jackson.property-naming-strategy=SNAKE_CASE
#spring.jackson.serialization.write-dates-as-timestamps=false
#jwt.valid-duration=5
#jwt.refreshable-duration=120
#spring.web.resources.static-locations=file:/E:/Thu/DATN/DATN_PoloHaven_backend/backend/uploads/nhan_vien/,file:/H:/FPT/DATN/150625/DATN_PoloHaven_backend/uploads/
#spring.web.resources.static-locations=file:uploads/
#spring.web.resources.static-locations=file:H:/FPT/DATN/150625/DATN_PoloHaven_backend/uploads/
# Cho phep multipart file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
upload.path=backend/uploads/san_pham
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:uploads/
spring.mvc.static-path-pattern=/uploads/**
#API Giao hang

#API Giao hang nhanh
ghn.api.url=https://online-gateway.ghn.vn/shiip/public-api/
ghn.api.token=a7719d89-583c-11f0-99f8-027692bb547c

# Shop ID
ghn.shop.hanoi=5871657
ghn.shop.hochiminh=5871670

# Fallback shipping fee
ghn.fallback.fee=30000
#Gui mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trendygenzcosmetic@gmail.com
spring.mail.password=uecdublvswxxwecx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
vnpay.tmnCode=2WMHC4A1
vnpay.hashSecret=GBDTVHSKE82IFT4794RN16DF56S48PBJ
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl= https://5474ddbf079c.ngrok-free.app/payment-result


#RETURN
vnpay.returnUrl=https://ded06ae9b666.ngrok-free.app/api/v1/payment/vnpay-payment-return

#api vnpay ngrok backend , http 8080
vnpay.ipnUrl=https://ded06ae9b666.ngrok-free.app/api/v1/payment/vnpay-ipn-callback


app.image.base-url=http://localhost:8080/uploads/san_pham/

# ngrok backend, http 8080
app.backend.base-url=https://ded06ae9b666.ngrok-free.app